title: "My Data Analytics Portfolio"
description: "Jupyter notebook portfolio"
baseurl: ""
url: "https://benng-kc.github.io"
markdown: kramdown
theme: minima
permalink: pretty
collections:
  notebooks:
    output: true
    permalink: /notebooks/:title/
