remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
<<<<<<< HEAD

title: "My Data Analytics Portfolio"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
=======
>>>>>>> bf72dc63d628ead3ed0695b72e7a63b454e00e21
