title: "My Data Analytics Portfolio"
description: "Jupyter notebook portfolio"
baseurl: "/portfolio"
url: "https://benng-kc.github.io"
markdown: kramdown
theme: null
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
