remote_theme: pages-themes/dinky@v0.2.0

title: "My Data Analytics Portfolio"
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
